//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataModel.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О нас.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В РАЗВЛЕКАТЕЛЬНЫЙ ЦЕНТР MEGA KIDS.
        /// </summary>
        public static string About_CompanyName {
            get {
                return ResourceManager.GetString("About_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sodales cursus ipsum, vitae venenatis neque ultrices lobortis. Duis eu nisl magna. In hac habitasse platea dictumst. Pellentesque nec diam sollicitudin, sollicitudin tellus eget, posuere ligula. Nulla ac mi eget urna congue molestie vel vitae arcu. Donec faucibus dui at mauris blandit, a pulvinar purus iaculis. Cras nec sodales risus. Morbi et turpis posuere, sollicitudin lectus ac, iaculis nulla. Aliquam non tortor sapien. Nunc ac mauris placerat, [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДОБРО ПОЖАЛОВАТЬ.
        /// </summary>
        public static string About_Welcome {
            get {
                return ResourceManager.GetString("About_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлено.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кафе.
        /// </summary>
        public static string Cafe {
            get {
                return ResourceManager.GetString("Cafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дни рождения.
        /// </summary>
        public static string Cafe_BirthDays {
            get {
                return ResourceManager.GetString("Cafe_BirthDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Детское меню.
        /// </summary>
        public static string Cafe_Menu {
            get {
                return ResourceManager.GetString("Cafe_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кафе для всей семьи.
        /// </summary>
        public static string Cafe_Title {
            get {
                return ResourceManager.GetString("Cafe_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Колонки.
        /// </summary>
        public static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Галерея.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Развлекательный центр MEGA KIDS.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ro.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новости.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вперед.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на другие фотоальбомы.
        /// </summary>
        public static string OtherAlbums {
            get {
                return ResourceManager.GetString("OtherAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фотоальбомы.
        /// </summary>
        public static string Photoalbums {
            get {
                return ResourceManager.GetString("Photoalbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подробнее.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последние новости.
        /// </summary>
        public static string RecentNews {
            get {
                return ResourceManager.GetString("RecentNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Услуги.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Content/Images/LogoRO.png.
        /// </summary>
        public static string SiteLogo {
            get {
                return ResourceManager.GetString("SiteLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видео.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смотри все новости.
        /// </summary>
        public static string WatchAllNews {
            get {
                return ResourceManager.GetString("WatchAllNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смотри еще.
        /// </summary>
        public static string WatchMore {
            get {
                return ResourceManager.GetString("WatchMore", resourceCulture);
            }
        }
    }
}
